import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from '../components/ui/theme-provider'
import NavBar from "@/components/ui/navbar";
import ClickSpark from "@/components/animations/ClickSpark/ClickSpark";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}  appearance={{
            elements: {
              modalBackdrop: "!bg-[#ffff]/10 ",
              card: "!backdrop-blur-md !bg-[rgba(13,19,30,0.2)] !border-white/20 !rounded-xl !shadow-2xl",
            }
          }} >
          <html lang="en" suppressHydrationWarning>
      <head>
              <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
            integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
            crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClickSpark
            sparkColor='#e3b605'
            sparkSize={15}
            sparkRadius={15}
            sparkCount={8}
            duration={400}
          >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="navbar fixed top-[0.6rem] left-1/2 -translate-x-1/2 z-50 ">
            <NavBar />
          </div>
          {/* <div className=" bg-amber-400 w-[100vw] h-[100vh] " >Helo</div> */}
          {children}
        </ThemeProvider>
      </ClickSpark>
      </body>
    </html>
    </ClerkProvider>
  );
}
